version: '2'

volumes:
  caddy_data:
  caddy_config:
  web_data:

services:
  haproxy:
    image: haproxy:latest
    restart: always
    ports:
      - 443:443
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    depends_on:
      - caddy
    links:
      - caddy:caddy

  caddy:
    image: caddy
    restart: always
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - web
    links:
      - web:web
    ports:
      - 80:80

  web:
    image: nginx:latest
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./.htpasswd:/etc/nginx/.htpasswd
